In [62]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [64]:
import numpy as np              #numpy short form-->np
import pandas as pd             ## same
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer #--> covert text to numreric value
from sklearn.metrics.pairwise import cosine_similarity #--> count the similarity score

In [65]:
movies_data = pd.read_csv('/content/drive/My Drive/BCT Gen AI/Movies_data.csv') #-->convert csv file to pandas frame
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

# Before the final project

---



In [66]:
movies_data.shape #number of rows&col

(4803, 24)

In [67]:
#feature extraction
selected_features = ['genres', 'keywords', 'original_language', 'tagline', 'cast', 'director']
selected_features

['genres', 'keywords', 'original_language', 'tagline', 'cast', 'director']

In [68]:
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')  # replacing the null value to null string

In [69]:
combined_features = movies_data['genres'] + ' ' + movies_data['keywords'] + ' ' + movies_data['original_language'] + ' ' + movies_data['tagline'] + ' ' + movies_data['cast'] + ' ' + movies_data['director']

In [70]:
combined_features

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  en A newlywed couple's honeymo...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      en A New Yorker in Shanghai Daniel Henney El...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [71]:
vectorizer = TfidfVectorizer()

In [72]:
feature_vectors = vectorizer.fit_transform(combined_features) #print combine feature to the vector/numerical values
print(feature_vectors)

  (0, 201)	0.07855333451401258
  (0, 274)	0.0901581919743486
  (0, 5281)	0.1110193583416378
  (0, 13614)	0.1035795705488959
  (0, 5444)	0.1035795705488959
  (0, 3682)	0.21379417528322506
  (0, 3067)	0.22195129200668778
  (0, 5843)	0.16457685199337505
  (0, 14394)	0.3394249143412073
  (0, 16607)	0.1254194588130164
  (0, 3228)	0.24945272753506634
  (0, 14287)	0.21379417528322506
  (0, 4911)	0.03453638093174036
  (0, 4950)	0.2401151966169693
  (0, 15279)	0.07091600479711817
  (0, 17018)	0.12813614591803602
  (0, 11202)	0.09043921375601768
  (0, 11513)	0.2719507691200355
  (0, 13364)	0.15012303027709265
  (0, 17027)	0.23629221686819424
  (0, 17312)	0.20185863312549773
  (0, 13334)	0.21761715503200013
  (0, 14079)	0.20583803637232168
  (0, 16688)	0.19831426292450677
  (0, 14624)	0.15141634132650295
  :	:
  (4801, 4839)	0.24697181882054414
  (4801, 17288)	0.2884161588693086
  (4801, 13850)	0.27851328266331316
  (4801, 13190)	0.2884161588693086
  (4801, 17171)	0.30237347896654454
  (4801, 351

In [73]:
similarity = cosine_similarity(feature_vectors) #measure the similarity score
print(similarity)

[[1.         0.0731602  0.03890829 ... 0.0012222  0.00126498 0.0011916 ]
 [0.0731602  1.         0.03384574 ... 0.0367837  0.00110423 0.00104018]
 [0.03890829 0.03384574 1.         ... 0.00125046 0.05512248 0.00121915]
 ...
 [0.0012222  0.0367837  0.00125046 ... 1.         0.00129619 0.02770363]
 [0.00126498 0.00110423 0.05512248 ... 0.00129619 1.         0.00126374]
 [0.0011916  0.00104018 0.00121915 ... 0.02770363 0.00126374 1.        ]]


In [74]:
similarity.shape #1-->movie index,2-->similarity score

(4803, 4803)

In [75]:
#Taking user input for their fav movie name
movie_name = input('Enter your favourite movie name : ')

Enter your favourite movie name : avatar


In [76]:
list_of_all_titles = movies_data['title'].tolist() #print the title name
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [77]:
#Getting close match of the movie given by the user
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
if len(find_close_match) == 0:
  print('No close match found')
else:
  print(find_close_match)

['Avatar']


In [78]:
close_match = find_close_match[0]  #print the fst match
print(close_match)

Avatar


In [79]:
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]  #print index of the movie
index_of_the_movie

0

In [80]:
# getting a list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie])) #enumerate-->is a kind of loop
print(similarity_score)   #fst is index,similarity score

[(0, 1.0), (1, 0.07316019619943206), (2, 0.038908294164221355), (3, 0.01383503882736602), (4, 0.10806287652504142), (5, 0.07900828046860506), (6, 0.009434442488574881), (7, 0.0372951498496873), (8, 0.030804723866848384), (9, 0.027432511013061565), (10, 0.09382702681727614), (11, 0.013763907341527925), (12, 0.0284022115363682), (13, 0.030636794478167046), (14, 0.07026229795485417), (15, 0.020668154179914865), (16, 0.035365897957214676), (17, 0.027171288356953784), (18, 0.05822204552553354), (19, 0.039944405708371225), (20, 0.0408554448298383), (21, 0.01300378564448258), (22, 0.031483106804805164), (23, 0.04691020431774924), (24, 0.047313096903626166), (25, 0.04399870917793088), (26, 0.07126243589121521), (27, 0.0382441357211949), (28, 0.041983515273569534), (29, 0.03978616315933167), (30, 0.08004475430405339), (31, 0.06165643501900889), (32, 0.03143274843359589), (33, 0.0370637028786442), (34, 0.0012097292232272929), (35, 0.0389054753469736), (36, 0.04999288566283571), (37, 0.0869101536

In [81]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)    #sorting the similar movies in decending order
print(sorted_similar_movies)

[(0, 1.0), (3158, 0.25026131398042306), (2403, 0.24938179415097078), (94, 0.24593462016484016), (56, 0.20484395247612705), (47, 0.20220630592780736), (1053, 0.1980117462226823), (838, 0.18119438163009546), (4593, 0.17542502762969134), (239, 0.1752995150024511), (3730, 0.17492206324006407), (1531, 0.16905634415534235), (2696, 0.165964557908573), (812, 0.16159450829037883), (4401, 0.1583415487673932), (643, 0.1574274285257613), (2198, 0.15321448194424384), (770, 0.1512124806551895), (2229, 0.1475209955176713), (1951, 0.1464579474194373), (1922, 0.1459669897146034), (206, 0.1432033937321821), (3208, 0.14119301404987603), (1759, 0.14010379834233558), (43, 0.135869835994392), (1473, 0.13574570452512952), (278, 0.1338186361296863), (158, 0.13362015259493334), (1650, 0.1311477519169239), (1275, 0.1270214605417775), (3439, 0.12590047605535448), (661, 0.12262914365061844), (3202, 0.122511547313196), (4332, 0.12089261765733966), (3105, 0.12065005704365112), (775, 0.11941206753215865), (1099, 0.1

In [82]:
print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  homepage_link = movies_data[movies_data.index==index]['homepage'].values[0]
  if (i<16):
    if pd.isna(homepage_link):
      print(i, '.',title_from_index, ' - page not available')
    else:
      print(i, '.',title_from_index, ' - ', homepage_link)
    i+=1

Movies suggested for you : 

1 . Avatar  -  http://www.avatarmovie.com/
2 . Alien  -  https://www.facebook.com/alienanthology/
3 . Aliens  - page not available
4 . Guardians of the Galaxy  -  http://marvel.com/guardians
5 . Star Trek Beyond  -  http://www.startrekmovie.com/
6 . Star Trek Into Darkness  - page not available
7 . Galaxy Quest  - page not available
8 . Alien³  - page not available
9 . Trekkies  - page not available
10 . Gravity  -  http://gravitymovie.warnerbros.com/
11 . Cargo  -  http://www.cargoderfilm.ch http://cargothemovie.com
12 . Moonraker  -  http://www.mgm.com/view/movie/1292/Moonraker/
13 . Jason X  - page not available
14 . Pocahontas  - page not available
15 . The Helix... Loaded  - page not available


# Movie Recommendation System

---



In [83]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

if len(find_close_match) == 0:
  print('No such movie or similar movies found!')

else:

  close_match = find_close_match[0]

  index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

  similarity_score = list(enumerate(similarity[index_of_the_movie]))

  sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

  print('\nMovies suggested for you : \n')

  i = 1

  for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_data[movies_data.index==index]['title'].values[0]
    homepage_link = movies_data[movies_data.index==index]['homepage'].values[0]
    if (i<16):
      if pd.isna(homepage_link):
        print(i, '.',title_from_index, ' - page not available')
      else:
        print(i, '.',title_from_index, ' - ', homepage_link)
      i+=1

 Enter your favourite movie name : super man

Movies suggested for you : 

1 . Superman  - page not available
2 . Superman II  - page not available
3 . Superman IV: The Quest for Peace  - page not available
4 . Man of Steel  -  http://www.manofsteel.com/
5 . Superman III  - page not available
6 . Crimson Tide  - page not available
7 . Superman Returns  -  http://www.superman.com
8 . Batman Returns  - page not available
9 . Suicide Squad  -  http://www.suicidesquad.com/
10 . The Killer Inside Me  -  http://www.killerinsideme.com/
11 . The Dark Knight Rises  -  http://www.thedarkknightrises.com/
12 . Nanny McPhee and the Big Bang  -  http://www.nannymcphee.co.uk/
13 . Batman Begins  -  http://www2.warnerbros.com/batmanbegins/index.html
14 . The Dark Knight  -  http://thedarkknight.warnerbros.com/dvdsite/
15 . The Godfather  -  http://www.thegodfather.com/
